name: meadote_inicio
description: Projeto Flutter MeAdote 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.0.0

  sqflite: ^2.3.0
  path: ^1.8.3

  font_awesome_flutter: ^10.7.0

  phosphor_flutter: ^2.0.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/meadote/logo/
    - assets/meadote/animais/
    - assets/meadote/campanhas/
    - assets/meadote/educacao/
    - assets/meadote/fundo/
    - assets/meadote/links/
    - assets/meadote/ongs/
    - assets/meadote/postagens/
